# @package model

defaults:
  - /model/architectures: dbnet
  - /model/optimizers: adamw
  - /model/encoder/timm_backbone
  - /model/decoder/unet
  - /model/head/db_head
  - /model/loss/db_loss
  - _self_

optimizer:
  lr: 0.001
  weight_decay: 0.0001

# Scheduler is now defined in the base model config
