
# Paths config - Index-based structure for reliability and easy sorting
experiment_dir: 'outputs'
log_dir: '${hydra:runtime.output_dir}/logs'
output_dir: '${hydra:runtime.output_dir}'
checkpoint_dir: '${hydra:runtime.output_dir}/checkpoints'
submission_dir: '${hydra:runtime.output_dir}/submissions'
