# @package _group_
# This file defines the callbacks that will be instantiated by Hydra.
# The `defaults` section includes individual callback configurations.
# Custom callbacks that don't have separate files are defined below.

defaults:
  - model_checkpoint@_group_.model_checkpoint
  - early_stopping@_group_.early_stopping
  - rich_progress_bar@_group_.rich_progress_bar
  - wandb_image_logging@_group_.wandb_image_logging
  - wandb_completion@_group_.wandb_completion
  - performance_profiler@_group_.performance_profiler
  - metadata@_group_.metadata  # Checkpoint Catalog V2: automatic metadata generation
  - _self_
