# @package _group_
# This file defines the callbacks that will be instantiated by Hydra.
# The `defaults` section includes individual callback configurations.
# Custom callbacks that don't have separate files are defined below.

defaults:
  - model_checkpoint
  - early_stopping
  - rich_progress_bar
  - wandb_image_logging
  - performance_profiler
  - metadata  # Checkpoint Catalog V2: automatic metadata generation
  - _self_

wandb_completion:
  _target_: ocr.core.lightning.callbacks.wandb_completion.WandbCompletionCallback
