defaults:
  - _self_
  - base                  # Keep for other settings
  - data: base            # Compose data group
  - data/performance_preset: none  # Default performance preset (no optimizations)
  - transforms: base      # Compose transforms group
  - dataloaders: default  # Compose dataloaders group
  - /preset/models/model_example
  - /preset/lightning_modules/base

# Override callbacks to match the checkpoint
callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: "val/loss"
    mode: "min"
    every_n_train_steps: 0
    every_n_epochs: 1
    train_time_interval: null

compile_model: false

seed: 42
exp_name: "ocr_prediction"
checkpoint_path: null #"outputs/ocr_training-dbnet-pan_decoder-resnet34/checkpoints/epoch_28_step_023722.ckpt" # resnet18 Â· step_014454 works too
image_dir: "LOW_PERFORMANCE_IMGS"
max_images: null
score_threshold: 0.01
save_dir: "outputs/prediction_visualization"
minified_json: False
include_confidence: False

# Optional overrides for DB postprocessor thresholds
postprocess_thresh: null
postprocess_box_thresh: null
postprocess_max_candidates: null
postprocess_use_polygon: null
