# @package _global_

defaults:
  - train_kie_aihub
  - _self_

debug: false
use_wandb: true

project_name: "ocr-kie-aihub-prod"
run_name: "kie-aihub-prod"

train:
  max_epochs: 30
  limit_train_batches: 1.0 # 1.0 means 100% of batches
  limit_val_batches: 1.0
