# @package trainer

# Consolidated trainer configuration
max_steps: -1
max_epochs: 3
num_sanity_val_steps: 1
log_every_n_steps: 20
val_check_interval: null
check_val_every_n_epoch: 1
deterministic: true
accumulate_grad_batches: 2
precision: "32-true"
benchmark: false
gradient_clip_val: 5.0
accelerator: gpu
devices: 1
strategy: auto

# Dataloader batch limits
limit_train_batches: null
limit_val_batches: null
limit_test_batches: null
